### ISSUE TITLE
Exception in GitUtil

### ISSUE THREAD

**Issue by OlegIlyenko** [OlegIlyenko/scumd#9]
Exception in thread "Execute:1300265748104" java.lang.RuntimeException: org.eclipse.jgit.errors.IncorrectObjectTypeException: Object 36425912b3e64f7d4625f86c431908a538151ea8 is not a commit.
at com.asolutions.scmsshd.util.GitUtil.traversePush(GitUtil.java:77)
at com.asolutions.scmsshd.commands.git.GitReceivePackSCMCommandHandler$1.onPreReceive(GitReceivePackSCMCommandHandler.java:75)
at org.eclipse.jgit.transport.ReceivePack.executeCommands(ReceivePack.java:985)
at org.eclipse.jgit.transport.ReceivePack.service(ReceivePack.java:646)
at org.eclipse.jgit.transport.ReceivePack.receive(ReceivePack.java:577)
at com.asolutions.scmsshd.commands.git.GitReceivePackSCMCommandHandler.runCommand(GitReceivePackSCMCommandHandler.java:124)
at com.asolutions.scmsshd.commands.git.GitSCMCommandImpl.execute(GitSCMCommandImpl.java:20)
at com.asolutions.scmsshd.commands.git.GitSCMCommandHandler.execute(GitSCMCommandHandler.java:28)
at com.asolutions.scmsshd.commands.git.SCMCommand.runImpl(SCMCommand.java:138)
at com.asolutions.scmsshd.commands.git.SCMCommand$1.run(SCMCommand.java:126)
Caused by: org.eclipse.jgit.errors.IncorrectObjectTypeException: Object 36425912b3e64f7d4625f86c431908a538151ea8 is not a commit.
at org.eclipse.jgit.storage.file.WindowCursor.open(WindowCursor.java:115)
at org.eclipse.jgit.revwalk.RevWalk.getCachedBytes(RevWalk.java:855)
at org.eclipse.jgit.revwalk.RevCommit.parseHeaders(RevCommit.java:136)
at org.eclipse.jgit.revwalk.RevWalk.markStart(RevWalk.java:282)
at com.asolutions.scmsshd.util.GitUtil.traversePush(GitUtil.java:38)
... 9 more

**Comment by OlegIlyenko** [comment]
Fixed... it was problem with commit traversing for tag creation push
